name: Deploy Cloud Run

# Questo workflow si esegue solo quando il workflow di versioning è completato
on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: google auth
          uses: 'google-github-actions/auth@v2'
          with:
            project_id: 'helical-song-449808-e5'
            credentials_json: ${{ secrets.GCP_SA_KEY }}

        - name: Configure Docker with Google Artifactory
          run: gcloud auth configure-docker europe-north1-docker.pkg.dev

        - id: 'deploy'
          run: |
            VERSION=latest
            IMAGE_URI=europe-north1-docker.pkg.dev/helical-song-449808-e5/docker-repo/tiziano093/graphql-server:latest
            
            gcloud run deploy graphql-server \
              --image $IMAGE_URI \
              --format json \
              --region europe-north1 \
              --platform managed \
              --allow-unauthenticated \
              --port 4000
