name: Deploy Cloud Run

# Questo workflow si esegue solo quando il workflow di versioning è completato
on:
  # workflow_run:
    # workflows: ["Build and Push Docker Image"]
    # types:
      # - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: google auth
          uses: 'google-github-actions/auth@v2'
          with:
            project_id: 'helical-song-449808-e5'
            credentials_json: ${{ secrets.GCP_SA_KEY }}

        - name: Configure Docker with Google Artifactory
          run: gcloud auth configure-docker ${{ secrets.REPO_LOCATION }}-docker.pkg.dev

        - id: 'deploy'
          run: |
            VERSION=${{ env.COMMIT_SHA }}
            IMAGE_URI=${{ secrets.REPO_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.CLOUD_REPO_NAME }}/$(basename ${{ github.repository }}):$VERSION
            
            gcloud run deploy $(basename ${{ github.repository }}) \
              --image $IMAGE_URI \
              --format json \
              --region ${{ secrets.DEPLOY_LOCATION }} \
              --platform managed \
              --allow-unauthenticated \
              --set-env-vars API_URL=https://net0-be-158747903386.europe-west8.run.app \
              --port ${{ secrets.PORT }}