name: Install and Test

on:
  pull_request:
    branches: 
      main
        
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          git config --global user.email "ci@example.com"
          git config --global user.name "CI Runner"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        
      - name: Lint
        run: npm run lint

      - name: Unit Test
        run: npm run test

      - name: Unit Test
        run: npm run test:coverage
